"""Remove subject field from notes

Revision ID: 4f4ef67e5c32
Revises: 76dda19f1140
Create Date: 2025-07-18 13:56:01.818741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4ef67e5c32'
down_revision: Union[str, None] = '76dda19f1140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
