"""removed repeats task option

Revision ID: 58f525cb1704
Revises: 257b37003e5d
Create Date: 2025-04-20 20:01:12.545556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58f525cb1704"
down_revision: Union[str, None] = "257b37003e5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_repeatable_id", table_name="tasks")
    op.drop_column("tasks", "repeatable_id")
    op.drop_column("tasks", "repeatable_days")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("repeatable_days", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tasks",
        sa.Column("repeatable_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_tasks_repeatable_id", "tasks", ["repeatable_id"], unique=False)
    # ### end Alembic commands ###
