"""Add Stripe fields to User

Revision ID: 7cb1232c4c3d
Revises: 8e74126e32af
Create Date: 2025-04-15 13:55:53.711945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cb1232c4c3d"
down_revision: Union[str, None] = "8e74126e32af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_subscribed", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("trial_start", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "trial_start")
    op.drop_column("users", "is_subscribed")
    op.drop_column("users", "stripe_customer_id")
    # ### end Alembic commands ###
